const menu = {
  products: [
    {
      id: 1,
      title: 'Café Americano',
      price: 5,
      category: 'breakfast',
      category2: 'Brebaje',
    },
    {
      id: 2,
      title: 'Café con leche',
      price: 7,
      category: 'breakfast',
      category2: 'Brebaje',
    },
    {
      id: 3,
      title: 'Jugo de frutas natural',
      price: 7,
      category: 'breakfast',
      category2: 'Brebaje',
    },
    {
      id: 4,
      title: 'Sandwich de jamón y queso',
      price: 10,
      category: 'breakfast',
      category2: 'Sandwich',
    },
    {
      id: 5,
      title: 'Sandwich palta',
      price: 10,
      category: 'breakfast',
      category2: 'Sandwich',
    },
    {
      id: 6,
      title: 'Agua 500ml',
      price: 5,
      category: 'afternoon',
      category2: 'Brebaje',
    },
    {
      id: 7,
      title: 'Agua 750ml',
      price: 7,
      category: 'afternoon',
      category2: 'Brebaje',
    },
    {
      id: 8,
      title: 'Bebida 500ml',
      price: 7,
      category: 'afternoon',
      category2: 'Brebaje',
    },
    {
      id: 9,
      title: 'Bebida 750ml',
      price: 10,
      category: 'afternoon',
      category2: 'Brebaje',
    },
    {
      id: 10,
      title: 'Hamburguesa Vegetariana Simple',
      price: 10,
      category: 'afternoon',
      category2: 'Hamburgesa',
    },
    {
      id: 11,
      title: 'Hamburguesa Vegetariana Doble',
      price: 15,
      category: 'afternoon',
      category2: 'Hamburgesa',
    },
    {
      id: 12,
      title: 'Hamburguesa Vacuno Simple',
      price: 10,
      category: 'afternoon',
      category2: 'Hamburgesa',
    },
    {
      id: 13,
      title: 'Hamburguesa Vacuno Doble',
      price: 15,
      category: 'afternoon',
      category2: 'Hamburgesa',
    },
    {
      id: 14,
      title: 'Hamburguesa Pollo Simple',
      price: 10,
      category: 'afternoon',
      category2: 'Hamburgesa',
    },
    {
      id: 15,
      title: 'Hamburguesa Pollo Doble',
      price: 15,
      category: 'afternoon',
      category2: 'Hamburgesa',
    },
    {
      id: 16,
      title: 'Agregado Queso',
      price: 1,
      category: 'afternoon',
      category2: 'Agregado',
    },
    {
      id: 17,
      title: 'Agregado Huevo',
      price: 1,
      category: 'afternoon',
      category2: 'Agregado',
    },
    {
      id: 18,
      title: 'Papas Fritas',
      price: 5,
      category: 'afternoon',
      category2: 'Acompañamiento',
    },
    {
      id: 19,
      title: 'Aros de Cebolla',
      price: 5,
      category: 'afternoon',
      category2: 'Acompañamiento',
    },
  ],
};

export default menu;
